import "@/css/globals.sass"
import { fontBody } from "@/libs/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          antialiased
          ${fontBody.className}
        `}
        
      >
        {children}
      </body>
    </html>
  );
}
