// Fonts
import { fontBody } from "@/libs/fonts"

// css
import "@/css/globals.sass"

// Global components
import Header from "@/components/layout/Header"
import Footer from "@/components/layout/Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          antialiased
          ${fontBody.className}
        `}

      >
        <Header />
          <main>
            {children}
          </main>
        <Footer />
      </body>
    </html>
  )
}
